
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install 'setuptools>=18.5'
    - pip install -r requirements.txt
    - pip install 'pytest>=3.6'
    - pip install pytest-cov
    - python setup.py develop

script:
    - pytest --cov=./alnitak

after_success:
    - bash <(curl -s https://codecov.io/bash)
